package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.List;

public class OrderCostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public OrderCostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqidIsNull() {
            addCriterion("`seqid` is null");
            return (Criteria) this;
        }

        public Criteria andSeqidIsNotNull() {
            addCriterion("`seqid` is not null");
            return (Criteria) this;
        }

        public Criteria andSeqidEqualTo(Long value) {
            addCriterion("`seqid` =", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidNotEqualTo(Long value) {
            addCriterion("`seqid` <>", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidGreaterThan(Long value) {
            addCriterion("`seqid` >", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidGreaterThanOrEqualTo(Long value) {
            addCriterion("`seqid` >=", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidLessThan(Long value) {
            addCriterion("`seqid` <", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidLessThanOrEqualTo(Long value) {
            addCriterion("`seqid` <=", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidIn(List<Long> values) {
            addCriterion("`seqid` in", values, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidNotIn(List<Long> values) {
            addCriterion("`seqid` not in", values, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidBetween(Long value1, Long value2) {
            addCriterion("`seqid` between", value1, value2, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidNotBetween(Long value1, Long value2) {
            addCriterion("`seqid` not between", value1, value2, "seqid");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("`orderid` is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("`orderid` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("`orderid` =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("`orderid` <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("`orderid` >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("`orderid` >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("`orderid` <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("`orderid` <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("`orderid` like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("`orderid` not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("`orderid` in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("`orderid` not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("`orderid` between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("`orderid` not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andLeaseIsNull() {
            addCriterion("`lease` is null");
            return (Criteria) this;
        }

        public Criteria andLeaseIsNotNull() {
            addCriterion("`lease` is not null");
            return (Criteria) this;
        }

        public Criteria andLeaseEqualTo(Byte value) {
            addCriterion("`lease` =", value, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseNotEqualTo(Byte value) {
            addCriterion("`lease` <>", value, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseGreaterThan(Byte value) {
            addCriterion("`lease` >", value, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseGreaterThanOrEqualTo(Byte value) {
            addCriterion("`lease` >=", value, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseLessThan(Byte value) {
            addCriterion("`lease` <", value, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseLessThanOrEqualTo(Byte value) {
            addCriterion("`lease` <=", value, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseIn(List<Byte> values) {
            addCriterion("`lease` in", values, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseNotIn(List<Byte> values) {
            addCriterion("`lease` not in", values, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseBetween(Byte value1, Byte value2) {
            addCriterion("`lease` between", value1, value2, "lease");
            return (Criteria) this;
        }

        public Criteria andLeaseNotBetween(Byte value1, Byte value2) {
            addCriterion("`lease` not between", value1, value2, "lease");
            return (Criteria) this;
        }

        public Criteria andFirst_costIsNull() {
            addCriterion("`first_cost` is null");
            return (Criteria) this;
        }

        public Criteria andFirst_costIsNotNull() {
            addCriterion("`first_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andFirst_costEqualTo(Integer value) {
            addCriterion("`first_cost` =", value, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costNotEqualTo(Integer value) {
            addCriterion("`first_cost` <>", value, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costGreaterThan(Integer value) {
            addCriterion("`first_cost` >", value, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`first_cost` >=", value, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costLessThan(Integer value) {
            addCriterion("`first_cost` <", value, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costLessThanOrEqualTo(Integer value) {
            addCriterion("`first_cost` <=", value, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costIn(List<Integer> values) {
            addCriterion("`first_cost` in", values, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costNotIn(List<Integer> values) {
            addCriterion("`first_cost` not in", values, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costBetween(Integer value1, Integer value2) {
            addCriterion("`first_cost` between", value1, value2, "first_cost");
            return (Criteria) this;
        }

        public Criteria andFirst_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`first_cost` not between", value1, value2, "first_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costIsNull() {
            addCriterion("`period_cost` is null");
            return (Criteria) this;
        }

        public Criteria andPeriod_costIsNotNull() {
            addCriterion("`period_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andPeriod_costEqualTo(Integer value) {
            addCriterion("`period_cost` =", value, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costNotEqualTo(Integer value) {
            addCriterion("`period_cost` <>", value, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costGreaterThan(Integer value) {
            addCriterion("`period_cost` >", value, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`period_cost` >=", value, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costLessThan(Integer value) {
            addCriterion("`period_cost` <", value, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costLessThanOrEqualTo(Integer value) {
            addCriterion("`period_cost` <=", value, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costIn(List<Integer> values) {
            addCriterion("`period_cost` in", values, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costNotIn(List<Integer> values) {
            addCriterion("`period_cost` not in", values, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costBetween(Integer value1, Integer value2) {
            addCriterion("`period_cost` between", value1, value2, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriod_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`period_cost` not between", value1, value2, "period_cost");
            return (Criteria) this;
        }

        public Criteria andPeriodsIsNull() {
            addCriterion("`periods` is null");
            return (Criteria) this;
        }

        public Criteria andPeriodsIsNotNull() {
            addCriterion("`periods` is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodsEqualTo(Byte value) {
            addCriterion("`periods` =", value, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsNotEqualTo(Byte value) {
            addCriterion("`periods` <>", value, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsGreaterThan(Byte value) {
            addCriterion("`periods` >", value, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsGreaterThanOrEqualTo(Byte value) {
            addCriterion("`periods` >=", value, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsLessThan(Byte value) {
            addCriterion("`periods` <", value, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsLessThanOrEqualTo(Byte value) {
            addCriterion("`periods` <=", value, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsIn(List<Byte> values) {
            addCriterion("`periods` in", values, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsNotIn(List<Byte> values) {
            addCriterion("`periods` not in", values, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsBetween(Byte value1, Byte value2) {
            addCriterion("`periods` between", value1, value2, "periods");
            return (Criteria) this;
        }

        public Criteria andPeriodsNotBetween(Byte value1, Byte value2) {
            addCriterion("`periods` not between", value1, value2, "periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsIsNull() {
            addCriterion("`left_periods` is null");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsIsNotNull() {
            addCriterion("`left_periods` is not null");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsEqualTo(Byte value) {
            addCriterion("`left_periods` =", value, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsNotEqualTo(Byte value) {
            addCriterion("`left_periods` <>", value, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsGreaterThan(Byte value) {
            addCriterion("`left_periods` >", value, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsGreaterThanOrEqualTo(Byte value) {
            addCriterion("`left_periods` >=", value, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsLessThan(Byte value) {
            addCriterion("`left_periods` <", value, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsLessThanOrEqualTo(Byte value) {
            addCriterion("`left_periods` <=", value, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsIn(List<Byte> values) {
            addCriterion("`left_periods` in", values, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsNotIn(List<Byte> values) {
            addCriterion("`left_periods` not in", values, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsBetween(Byte value1, Byte value2) {
            addCriterion("`left_periods` between", value1, value2, "left_periods");
            return (Criteria) this;
        }

        public Criteria andLeft_periodsNotBetween(Byte value1, Byte value2) {
            addCriterion("`left_periods` not between", value1, value2, "left_periods");
            return (Criteria) this;
        }

        public Criteria andBuyout_costIsNull() {
            addCriterion("`buyout_cost` is null");
            return (Criteria) this;
        }

        public Criteria andBuyout_costIsNotNull() {
            addCriterion("`buyout_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andBuyout_costEqualTo(Integer value) {
            addCriterion("`buyout_cost` =", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costNotEqualTo(Integer value) {
            addCriterion("`buyout_cost` <>", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costGreaterThan(Integer value) {
            addCriterion("`buyout_cost` >", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost` >=", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costLessThan(Integer value) {
            addCriterion("`buyout_cost` <", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costLessThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost` <=", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costIn(List<Integer> values) {
            addCriterion("`buyout_cost` in", values, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costNotIn(List<Integer> values) {
            addCriterion("`buyout_cost` not in", values, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costBetween(Integer value1, Integer value2) {
            addCriterion("`buyout_cost` between", value1, value2, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`buyout_cost` not between", value1, value2, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costIsNull() {
            addCriterion("`offset_cost` is null");
            return (Criteria) this;
        }

        public Criteria andOffset_costIsNotNull() {
            addCriterion("`offset_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andOffset_costEqualTo(Integer value) {
            addCriterion("`offset_cost` =", value, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costNotEqualTo(Integer value) {
            addCriterion("`offset_cost` <>", value, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costGreaterThan(Integer value) {
            addCriterion("`offset_cost` >", value, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`offset_cost` >=", value, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costLessThan(Integer value) {
            addCriterion("`offset_cost` <", value, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costLessThanOrEqualTo(Integer value) {
            addCriterion("`offset_cost` <=", value, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costIn(List<Integer> values) {
            addCriterion("`offset_cost` in", values, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costNotIn(List<Integer> values) {
            addCriterion("`offset_cost` not in", values, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costBetween(Integer value1, Integer value2) {
            addCriterion("`offset_cost` between", value1, value2, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andOffset_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`offset_cost` not between", value1, value2, "offset_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costIsNull() {
            addCriterion("`credit_cost` is null");
            return (Criteria) this;
        }

        public Criteria andCredit_costIsNotNull() {
            addCriterion("`credit_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andCredit_costEqualTo(Integer value) {
            addCriterion("`credit_cost` =", value, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costNotEqualTo(Integer value) {
            addCriterion("`credit_cost` <>", value, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costGreaterThan(Integer value) {
            addCriterion("`credit_cost` >", value, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`credit_cost` >=", value, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costLessThan(Integer value) {
            addCriterion("`credit_cost` <", value, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costLessThanOrEqualTo(Integer value) {
            addCriterion("`credit_cost` <=", value, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costIn(List<Integer> values) {
            addCriterion("`credit_cost` in", values, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costNotIn(List<Integer> values) {
            addCriterion("`credit_cost` not in", values, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costBetween(Integer value1, Integer value2) {
            addCriterion("`credit_cost` between", value1, value2, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andCredit_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`credit_cost` not between", value1, value2, "credit_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costIsNull() {
            addCriterion("`total_cost` is null");
            return (Criteria) this;
        }

        public Criteria andTotal_costIsNotNull() {
            addCriterion("`total_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_costEqualTo(Integer value) {
            addCriterion("`total_cost` =", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costNotEqualTo(Integer value) {
            addCriterion("`total_cost` <>", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costGreaterThan(Integer value) {
            addCriterion("`total_cost` >", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`total_cost` >=", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costLessThan(Integer value) {
            addCriterion("`total_cost` <", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costLessThanOrEqualTo(Integer value) {
            addCriterion("`total_cost` <=", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costIn(List<Integer> values) {
            addCriterion("`total_cost` in", values, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costNotIn(List<Integer> values) {
            addCriterion("`total_cost` not in", values, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costBetween(Integer value1, Integer value2) {
            addCriterion("`total_cost` between", value1, value2, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`total_cost` not between", value1, value2, "total_cost");
            return (Criteria) this;
        }

        public Criteria andPeriods2IsNull() {
            addCriterion("`periods2` is null");
            return (Criteria) this;
        }

        public Criteria andPeriods2IsNotNull() {
            addCriterion("`periods2` is not null");
            return (Criteria) this;
        }

        public Criteria andPeriods2EqualTo(Integer value) {
            addCriterion("`periods2` =", value, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2NotEqualTo(Integer value) {
            addCriterion("`periods2` <>", value, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2GreaterThan(Integer value) {
            addCriterion("`periods2` >", value, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`periods2` >=", value, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2LessThan(Integer value) {
            addCriterion("`periods2` <", value, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2LessThanOrEqualTo(Integer value) {
            addCriterion("`periods2` <=", value, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2In(List<Integer> values) {
            addCriterion("`periods2` in", values, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2NotIn(List<Integer> values) {
            addCriterion("`periods2` not in", values, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2Between(Integer value1, Integer value2) {
            addCriterion("`periods2` between", value1, value2, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriods2NotBetween(Integer value1, Integer value2) {
            addCriterion("`periods2` not between", value1, value2, "periods2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2IsNull() {
            addCriterion("`period_cost2` is null");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2IsNotNull() {
            addCriterion("`period_cost2` is not null");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2EqualTo(Integer value) {
            addCriterion("`period_cost2` =", value, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2NotEqualTo(Integer value) {
            addCriterion("`period_cost2` <>", value, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2GreaterThan(Integer value) {
            addCriterion("`period_cost2` >", value, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`period_cost2` >=", value, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2LessThan(Integer value) {
            addCriterion("`period_cost2` <", value, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2LessThanOrEqualTo(Integer value) {
            addCriterion("`period_cost2` <=", value, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2In(List<Integer> values) {
            addCriterion("`period_cost2` in", values, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2NotIn(List<Integer> values) {
            addCriterion("`period_cost2` not in", values, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2Between(Integer value1, Integer value2) {
            addCriterion("`period_cost2` between", value1, value2, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andPeriod_cost2NotBetween(Integer value1, Integer value2) {
            addCriterion("`period_cost2` not between", value1, value2, "period_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2IsNull() {
            addCriterion("`buyout_cost2` is null");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2IsNotNull() {
            addCriterion("`buyout_cost2` is not null");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2EqualTo(Integer value) {
            addCriterion("`buyout_cost2` =", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2NotEqualTo(Integer value) {
            addCriterion("`buyout_cost2` <>", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2GreaterThan(Integer value) {
            addCriterion("`buyout_cost2` >", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost2` >=", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2LessThan(Integer value) {
            addCriterion("`buyout_cost2` <", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2LessThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost2` <=", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2In(List<Integer> values) {
            addCriterion("`buyout_cost2` in", values, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2NotIn(List<Integer> values) {
            addCriterion("`buyout_cost2` not in", values, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2Between(Integer value1, Integer value2) {
            addCriterion("`buyout_cost2` between", value1, value2, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2NotBetween(Integer value1, Integer value2) {
            addCriterion("`buyout_cost2` not between", value1, value2, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2IsNull() {
            addCriterion("`total_cost2` is null");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2IsNotNull() {
            addCriterion("`total_cost2` is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2EqualTo(Integer value) {
            addCriterion("`total_cost2` =", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2NotEqualTo(Integer value) {
            addCriterion("`total_cost2` <>", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2GreaterThan(Integer value) {
            addCriterion("`total_cost2` >", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`total_cost2` >=", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2LessThan(Integer value) {
            addCriterion("`total_cost2` <", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2LessThanOrEqualTo(Integer value) {
            addCriterion("`total_cost2` <=", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2In(List<Integer> values) {
            addCriterion("`total_cost2` in", values, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2NotIn(List<Integer> values) {
            addCriterion("`total_cost2` not in", values, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2Between(Integer value1, Integer value2) {
            addCriterion("`total_cost2` between", value1, value2, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2NotBetween(Integer value1, Integer value2) {
            addCriterion("`total_cost2` not between", value1, value2, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_depositIsNull() {
            addCriterion("`total_deposit` is null");
            return (Criteria) this;
        }

        public Criteria andTotal_depositIsNotNull() {
            addCriterion("`total_deposit` is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_depositEqualTo(Integer value) {
            addCriterion("`total_deposit` =", value, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositNotEqualTo(Integer value) {
            addCriterion("`total_deposit` <>", value, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositGreaterThan(Integer value) {
            addCriterion("`total_deposit` >", value, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositGreaterThanOrEqualTo(Integer value) {
            addCriterion("`total_deposit` >=", value, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositLessThan(Integer value) {
            addCriterion("`total_deposit` <", value, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositLessThanOrEqualTo(Integer value) {
            addCriterion("`total_deposit` <=", value, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositIn(List<Integer> values) {
            addCriterion("`total_deposit` in", values, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositNotIn(List<Integer> values) {
            addCriterion("`total_deposit` not in", values, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositBetween(Integer value1, Integer value2) {
            addCriterion("`total_deposit` between", value1, value2, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andTotal_depositNotBetween(Integer value1, Integer value2) {
            addCriterion("`total_deposit` not between", value1, value2, "total_deposit");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNull() {
            addCriterion("`premium` is null");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNotNull() {
            addCriterion("`premium` is not null");
            return (Criteria) this;
        }

        public Criteria andPremiumEqualTo(Integer value) {
            addCriterion("`premium` =", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotEqualTo(Integer value) {
            addCriterion("`premium` <>", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThan(Integer value) {
            addCriterion("`premium` >", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`premium` >=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThan(Integer value) {
            addCriterion("`premium` <", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThanOrEqualTo(Integer value) {
            addCriterion("`premium` <=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumIn(List<Integer> values) {
            addCriterion("`premium` in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotIn(List<Integer> values) {
            addCriterion("`premium` not in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumBetween(Integer value1, Integer value2) {
            addCriterion("`premium` between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotBetween(Integer value1, Integer value2) {
            addCriterion("`premium` not between", value1, value2, "premium");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_cost_1
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 23 15:34:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}