package com.zdd.risk.bean;

public class OrderCost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.seqid
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Long seqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.orderid
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.lease
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Byte lease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.first_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer first_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.period_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer period_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.periods
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Byte periods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.left_periods
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Byte left_periods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.buyout_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer buyout_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.offset_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer offset_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.credit_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer credit_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.total_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer total_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.periods2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer periods2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.period_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer period_cost2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.buyout_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer buyout_cost2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.total_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer total_cost2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.total_deposit
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer total_deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.premium
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private Integer premium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.activity_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private String activity_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.insurance_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private String insurance_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.coupon_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private String coupon_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cost_1.discount_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    private String discount_info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.seqid
     *
     * @return the value of order_cost_1.seqid
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Long getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.seqid
     *
     * @param seqid the value for order_cost_1.seqid
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setSeqid(Long seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.orderid
     *
     * @return the value of order_cost_1.orderid
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.orderid
     *
     * @param orderid the value for order_cost_1.orderid
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.lease
     *
     * @return the value of order_cost_1.lease
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Byte getLease() {
        return lease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.lease
     *
     * @param lease the value for order_cost_1.lease
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setLease(Byte lease) {
        this.lease = lease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.first_cost
     *
     * @return the value of order_cost_1.first_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getFirst_cost() {
        return first_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.first_cost
     *
     * @param first_cost the value for order_cost_1.first_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setFirst_cost(Integer first_cost) {
        this.first_cost = first_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.period_cost
     *
     * @return the value of order_cost_1.period_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getPeriod_cost() {
        return period_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.period_cost
     *
     * @param period_cost the value for order_cost_1.period_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setPeriod_cost(Integer period_cost) {
        this.period_cost = period_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.periods
     *
     * @return the value of order_cost_1.periods
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Byte getPeriods() {
        return periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.periods
     *
     * @param periods the value for order_cost_1.periods
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setPeriods(Byte periods) {
        this.periods = periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.left_periods
     *
     * @return the value of order_cost_1.left_periods
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Byte getLeft_periods() {
        return left_periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.left_periods
     *
     * @param left_periods the value for order_cost_1.left_periods
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setLeft_periods(Byte left_periods) {
        this.left_periods = left_periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.buyout_cost
     *
     * @return the value of order_cost_1.buyout_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getBuyout_cost() {
        return buyout_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.buyout_cost
     *
     * @param buyout_cost the value for order_cost_1.buyout_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setBuyout_cost(Integer buyout_cost) {
        this.buyout_cost = buyout_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.offset_cost
     *
     * @return the value of order_cost_1.offset_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getOffset_cost() {
        return offset_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.offset_cost
     *
     * @param offset_cost the value for order_cost_1.offset_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setOffset_cost(Integer offset_cost) {
        this.offset_cost = offset_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.credit_cost
     *
     * @return the value of order_cost_1.credit_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getCredit_cost() {
        return credit_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.credit_cost
     *
     * @param credit_cost the value for order_cost_1.credit_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setCredit_cost(Integer credit_cost) {
        this.credit_cost = credit_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.total_cost
     *
     * @return the value of order_cost_1.total_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getTotal_cost() {
        return total_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.total_cost
     *
     * @param total_cost the value for order_cost_1.total_cost
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setTotal_cost(Integer total_cost) {
        this.total_cost = total_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.periods2
     *
     * @return the value of order_cost_1.periods2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getPeriods2() {
        return periods2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.periods2
     *
     * @param periods2 the value for order_cost_1.periods2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setPeriods2(Integer periods2) {
        this.periods2 = periods2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.period_cost2
     *
     * @return the value of order_cost_1.period_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getPeriod_cost2() {
        return period_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.period_cost2
     *
     * @param period_cost2 the value for order_cost_1.period_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setPeriod_cost2(Integer period_cost2) {
        this.period_cost2 = period_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.buyout_cost2
     *
     * @return the value of order_cost_1.buyout_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getBuyout_cost2() {
        return buyout_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.buyout_cost2
     *
     * @param buyout_cost2 the value for order_cost_1.buyout_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setBuyout_cost2(Integer buyout_cost2) {
        this.buyout_cost2 = buyout_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.total_cost2
     *
     * @return the value of order_cost_1.total_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getTotal_cost2() {
        return total_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.total_cost2
     *
     * @param total_cost2 the value for order_cost_1.total_cost2
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setTotal_cost2(Integer total_cost2) {
        this.total_cost2 = total_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.total_deposit
     *
     * @return the value of order_cost_1.total_deposit
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getTotal_deposit() {
        return total_deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.total_deposit
     *
     * @param total_deposit the value for order_cost_1.total_deposit
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setTotal_deposit(Integer total_deposit) {
        this.total_deposit = total_deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.premium
     *
     * @return the value of order_cost_1.premium
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public Integer getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.premium
     *
     * @param premium the value for order_cost_1.premium
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setPremium(Integer premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.activity_info
     *
     * @return the value of order_cost_1.activity_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public String getActivity_info() {
        return activity_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.activity_info
     *
     * @param activity_info the value for order_cost_1.activity_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setActivity_info(String activity_info) {
        this.activity_info = activity_info == null ? null : activity_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.insurance_info
     *
     * @return the value of order_cost_1.insurance_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public String getInsurance_info() {
        return insurance_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.insurance_info
     *
     * @param insurance_info the value for order_cost_1.insurance_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setInsurance_info(String insurance_info) {
        this.insurance_info = insurance_info == null ? null : insurance_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.coupon_info
     *
     * @return the value of order_cost_1.coupon_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public String getCoupon_info() {
        return coupon_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.coupon_info
     *
     * @param coupon_info the value for order_cost_1.coupon_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setCoupon_info(String coupon_info) {
        this.coupon_info = coupon_info == null ? null : coupon_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cost_1.discount_info
     *
     * @return the value of order_cost_1.discount_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public String getDiscount_info() {
        return discount_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cost_1.discount_info
     *
     * @param discount_info the value for order_cost_1.discount_info
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    public void setDiscount_info(String discount_info) {
        this.discount_info = discount_info == null ? null : discount_info.trim();
    }
}