package com.zdd.risk.bean;

public class ProductPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.priceid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer priceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.productid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.configid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private String configid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.ram
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte ram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.rom
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte rom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.net
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte net;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.channel
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.version
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.fineness
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte fineness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.color
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.months
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte months;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.month_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer month_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.total_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer total_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.buyout_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer buyout_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.months2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte months2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.month_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer month_cost2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.total_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer total_cost2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.buyout_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer buyout_cost2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.free_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte free_ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.surplus_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte surplus_ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.market
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.deposit_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer deposit_ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.deposit
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.deposit_ratio2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer deposit_ratio2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.deposit2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer deposit2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.premium
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer premium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.sales_limit
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer sales_limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.sales_total
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer sales_total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.sales_temp
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Integer sales_temp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.orderno
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Long orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.status
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.ymdhms
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private String ymdhms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_1.refuse_reason
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    private String refuse_reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.priceid
     *
     * @return the value of product_price_1.priceid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getPriceid() {
        return priceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.priceid
     *
     * @param priceid the value for product_price_1.priceid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setPriceid(Integer priceid) {
        this.priceid = priceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.productid
     *
     * @return the value of product_price_1.productid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.productid
     *
     * @param productid the value for product_price_1.productid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.configid
     *
     * @return the value of product_price_1.configid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public String getConfigid() {
        return configid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.configid
     *
     * @param configid the value for product_price_1.configid
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setConfigid(String configid) {
        this.configid = configid == null ? null : configid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.ram
     *
     * @return the value of product_price_1.ram
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getRam() {
        return ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.ram
     *
     * @param ram the value for product_price_1.ram
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setRam(Byte ram) {
        this.ram = ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.rom
     *
     * @return the value of product_price_1.rom
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getRom() {
        return rom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.rom
     *
     * @param rom the value for product_price_1.rom
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setRom(Byte rom) {
        this.rom = rom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.net
     *
     * @return the value of product_price_1.net
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getNet() {
        return net;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.net
     *
     * @param net the value for product_price_1.net
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setNet(Byte net) {
        this.net = net;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.channel
     *
     * @return the value of product_price_1.channel
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.channel
     *
     * @param channel the value for product_price_1.channel
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.version
     *
     * @return the value of product_price_1.version
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.version
     *
     * @param version the value for product_price_1.version
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setVersion(Byte version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.fineness
     *
     * @return the value of product_price_1.fineness
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getFineness() {
        return fineness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.fineness
     *
     * @param fineness the value for product_price_1.fineness
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setFineness(Byte fineness) {
        this.fineness = fineness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.color
     *
     * @return the value of product_price_1.color
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.color
     *
     * @param color the value for product_price_1.color
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setColor(Byte color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.months
     *
     * @return the value of product_price_1.months
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.months
     *
     * @param months the value for product_price_1.months
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setMonths(Byte months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.month_cost
     *
     * @return the value of product_price_1.month_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getMonth_cost() {
        return month_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.month_cost
     *
     * @param month_cost the value for product_price_1.month_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setMonth_cost(Integer month_cost) {
        this.month_cost = month_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.total_cost
     *
     * @return the value of product_price_1.total_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getTotal_cost() {
        return total_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.total_cost
     *
     * @param total_cost the value for product_price_1.total_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setTotal_cost(Integer total_cost) {
        this.total_cost = total_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.buyout_cost
     *
     * @return the value of product_price_1.buyout_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getBuyout_cost() {
        return buyout_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.buyout_cost
     *
     * @param buyout_cost the value for product_price_1.buyout_cost
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setBuyout_cost(Integer buyout_cost) {
        this.buyout_cost = buyout_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.months2
     *
     * @return the value of product_price_1.months2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getMonths2() {
        return months2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.months2
     *
     * @param months2 the value for product_price_1.months2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setMonths2(Byte months2) {
        this.months2 = months2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.month_cost2
     *
     * @return the value of product_price_1.month_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getMonth_cost2() {
        return month_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.month_cost2
     *
     * @param month_cost2 the value for product_price_1.month_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setMonth_cost2(Integer month_cost2) {
        this.month_cost2 = month_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.total_cost2
     *
     * @return the value of product_price_1.total_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getTotal_cost2() {
        return total_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.total_cost2
     *
     * @param total_cost2 the value for product_price_1.total_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setTotal_cost2(Integer total_cost2) {
        this.total_cost2 = total_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.buyout_cost2
     *
     * @return the value of product_price_1.buyout_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getBuyout_cost2() {
        return buyout_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.buyout_cost2
     *
     * @param buyout_cost2 the value for product_price_1.buyout_cost2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setBuyout_cost2(Integer buyout_cost2) {
        this.buyout_cost2 = buyout_cost2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.free_ratio
     *
     * @return the value of product_price_1.free_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getFree_ratio() {
        return free_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.free_ratio
     *
     * @param free_ratio the value for product_price_1.free_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setFree_ratio(Byte free_ratio) {
        this.free_ratio = free_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.surplus_ratio
     *
     * @return the value of product_price_1.surplus_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getSurplus_ratio() {
        return surplus_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.surplus_ratio
     *
     * @param surplus_ratio the value for product_price_1.surplus_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setSurplus_ratio(Byte surplus_ratio) {
        this.surplus_ratio = surplus_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.market
     *
     * @return the value of product_price_1.market
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.market
     *
     * @param market the value for product_price_1.market
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setMarket(Integer market) {
        this.market = market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.deposit_ratio
     *
     * @return the value of product_price_1.deposit_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getDeposit_ratio() {
        return deposit_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.deposit_ratio
     *
     * @param deposit_ratio the value for product_price_1.deposit_ratio
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setDeposit_ratio(Integer deposit_ratio) {
        this.deposit_ratio = deposit_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.deposit
     *
     * @return the value of product_price_1.deposit
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.deposit
     *
     * @param deposit the value for product_price_1.deposit
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.deposit_ratio2
     *
     * @return the value of product_price_1.deposit_ratio2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getDeposit_ratio2() {
        return deposit_ratio2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.deposit_ratio2
     *
     * @param deposit_ratio2 the value for product_price_1.deposit_ratio2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setDeposit_ratio2(Integer deposit_ratio2) {
        this.deposit_ratio2 = deposit_ratio2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.deposit2
     *
     * @return the value of product_price_1.deposit2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getDeposit2() {
        return deposit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.deposit2
     *
     * @param deposit2 the value for product_price_1.deposit2
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setDeposit2(Integer deposit2) {
        this.deposit2 = deposit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.premium
     *
     * @return the value of product_price_1.premium
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.premium
     *
     * @param premium the value for product_price_1.premium
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setPremium(Integer premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.sales_limit
     *
     * @return the value of product_price_1.sales_limit
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getSales_limit() {
        return sales_limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.sales_limit
     *
     * @param sales_limit the value for product_price_1.sales_limit
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setSales_limit(Integer sales_limit) {
        this.sales_limit = sales_limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.sales_total
     *
     * @return the value of product_price_1.sales_total
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getSales_total() {
        return sales_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.sales_total
     *
     * @param sales_total the value for product_price_1.sales_total
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setSales_total(Integer sales_total) {
        this.sales_total = sales_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.sales_temp
     *
     * @return the value of product_price_1.sales_temp
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Integer getSales_temp() {
        return sales_temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.sales_temp
     *
     * @param sales_temp the value for product_price_1.sales_temp
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setSales_temp(Integer sales_temp) {
        this.sales_temp = sales_temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.orderno
     *
     * @return the value of product_price_1.orderno
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Long getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.orderno
     *
     * @param orderno the value for product_price_1.orderno
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setOrderno(Long orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.status
     *
     * @return the value of product_price_1.status
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.status
     *
     * @param status the value for product_price_1.status
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.ymdhms
     *
     * @return the value of product_price_1.ymdhms
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public String getYmdhms() {
        return ymdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.ymdhms
     *
     * @param ymdhms the value for product_price_1.ymdhms
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setYmdhms(String ymdhms) {
        this.ymdhms = ymdhms == null ? null : ymdhms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_1.refuse_reason
     *
     * @return the value of product_price_1.refuse_reason
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public String getRefuse_reason() {
        return refuse_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_1.refuse_reason
     *
     * @param refuse_reason the value for product_price_1.refuse_reason
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setRefuse_reason(String refuse_reason) {
        this.refuse_reason = refuse_reason == null ? null : refuse_reason.trim();
    }
}