package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.List;

public class ProductPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public ProductPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPriceidIsNull() {
            addCriterion("`priceid` is null");
            return (Criteria) this;
        }

        public Criteria andPriceidIsNotNull() {
            addCriterion("`priceid` is not null");
            return (Criteria) this;
        }

        public Criteria andPriceidEqualTo(Integer value) {
            addCriterion("`priceid` =", value, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidNotEqualTo(Integer value) {
            addCriterion("`priceid` <>", value, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidGreaterThan(Integer value) {
            addCriterion("`priceid` >", value, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`priceid` >=", value, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidLessThan(Integer value) {
            addCriterion("`priceid` <", value, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidLessThanOrEqualTo(Integer value) {
            addCriterion("`priceid` <=", value, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidIn(List<Integer> values) {
            addCriterion("`priceid` in", values, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidNotIn(List<Integer> values) {
            addCriterion("`priceid` not in", values, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidBetween(Integer value1, Integer value2) {
            addCriterion("`priceid` between", value1, value2, "priceid");
            return (Criteria) this;
        }

        public Criteria andPriceidNotBetween(Integer value1, Integer value2) {
            addCriterion("`priceid` not between", value1, value2, "priceid");
            return (Criteria) this;
        }

        public Criteria andProductidIsNull() {
            addCriterion("`productid` is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("`productid` is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Integer value) {
            addCriterion("`productid` =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Integer value) {
            addCriterion("`productid` <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Integer value) {
            addCriterion("`productid` >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`productid` >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Integer value) {
            addCriterion("`productid` <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Integer value) {
            addCriterion("`productid` <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Integer> values) {
            addCriterion("`productid` in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Integer> values) {
            addCriterion("`productid` not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Integer value1, Integer value2) {
            addCriterion("`productid` between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Integer value1, Integer value2) {
            addCriterion("`productid` not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andConfigidIsNull() {
            addCriterion("`configid` is null");
            return (Criteria) this;
        }

        public Criteria andConfigidIsNotNull() {
            addCriterion("`configid` is not null");
            return (Criteria) this;
        }

        public Criteria andConfigidEqualTo(String value) {
            addCriterion("`configid` =", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidNotEqualTo(String value) {
            addCriterion("`configid` <>", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidGreaterThan(String value) {
            addCriterion("`configid` >", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidGreaterThanOrEqualTo(String value) {
            addCriterion("`configid` >=", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidLessThan(String value) {
            addCriterion("`configid` <", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidLessThanOrEqualTo(String value) {
            addCriterion("`configid` <=", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidLike(String value) {
            addCriterion("`configid` like", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidNotLike(String value) {
            addCriterion("`configid` not like", value, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidIn(List<String> values) {
            addCriterion("`configid` in", values, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidNotIn(List<String> values) {
            addCriterion("`configid` not in", values, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidBetween(String value1, String value2) {
            addCriterion("`configid` between", value1, value2, "configid");
            return (Criteria) this;
        }

        public Criteria andConfigidNotBetween(String value1, String value2) {
            addCriterion("`configid` not between", value1, value2, "configid");
            return (Criteria) this;
        }

        public Criteria andRamIsNull() {
            addCriterion("`ram` is null");
            return (Criteria) this;
        }

        public Criteria andRamIsNotNull() {
            addCriterion("`ram` is not null");
            return (Criteria) this;
        }

        public Criteria andRamEqualTo(Byte value) {
            addCriterion("`ram` =", value, "ram");
            return (Criteria) this;
        }

        public Criteria andRamNotEqualTo(Byte value) {
            addCriterion("`ram` <>", value, "ram");
            return (Criteria) this;
        }

        public Criteria andRamGreaterThan(Byte value) {
            addCriterion("`ram` >", value, "ram");
            return (Criteria) this;
        }

        public Criteria andRamGreaterThanOrEqualTo(Byte value) {
            addCriterion("`ram` >=", value, "ram");
            return (Criteria) this;
        }

        public Criteria andRamLessThan(Byte value) {
            addCriterion("`ram` <", value, "ram");
            return (Criteria) this;
        }

        public Criteria andRamLessThanOrEqualTo(Byte value) {
            addCriterion("`ram` <=", value, "ram");
            return (Criteria) this;
        }

        public Criteria andRamIn(List<Byte> values) {
            addCriterion("`ram` in", values, "ram");
            return (Criteria) this;
        }

        public Criteria andRamNotIn(List<Byte> values) {
            addCriterion("`ram` not in", values, "ram");
            return (Criteria) this;
        }

        public Criteria andRamBetween(Byte value1, Byte value2) {
            addCriterion("`ram` between", value1, value2, "ram");
            return (Criteria) this;
        }

        public Criteria andRamNotBetween(Byte value1, Byte value2) {
            addCriterion("`ram` not between", value1, value2, "ram");
            return (Criteria) this;
        }

        public Criteria andRomIsNull() {
            addCriterion("`rom` is null");
            return (Criteria) this;
        }

        public Criteria andRomIsNotNull() {
            addCriterion("`rom` is not null");
            return (Criteria) this;
        }

        public Criteria andRomEqualTo(Byte value) {
            addCriterion("`rom` =", value, "rom");
            return (Criteria) this;
        }

        public Criteria andRomNotEqualTo(Byte value) {
            addCriterion("`rom` <>", value, "rom");
            return (Criteria) this;
        }

        public Criteria andRomGreaterThan(Byte value) {
            addCriterion("`rom` >", value, "rom");
            return (Criteria) this;
        }

        public Criteria andRomGreaterThanOrEqualTo(Byte value) {
            addCriterion("`rom` >=", value, "rom");
            return (Criteria) this;
        }

        public Criteria andRomLessThan(Byte value) {
            addCriterion("`rom` <", value, "rom");
            return (Criteria) this;
        }

        public Criteria andRomLessThanOrEqualTo(Byte value) {
            addCriterion("`rom` <=", value, "rom");
            return (Criteria) this;
        }

        public Criteria andRomIn(List<Byte> values) {
            addCriterion("`rom` in", values, "rom");
            return (Criteria) this;
        }

        public Criteria andRomNotIn(List<Byte> values) {
            addCriterion("`rom` not in", values, "rom");
            return (Criteria) this;
        }

        public Criteria andRomBetween(Byte value1, Byte value2) {
            addCriterion("`rom` between", value1, value2, "rom");
            return (Criteria) this;
        }

        public Criteria andRomNotBetween(Byte value1, Byte value2) {
            addCriterion("`rom` not between", value1, value2, "rom");
            return (Criteria) this;
        }

        public Criteria andNetIsNull() {
            addCriterion("`net` is null");
            return (Criteria) this;
        }

        public Criteria andNetIsNotNull() {
            addCriterion("`net` is not null");
            return (Criteria) this;
        }

        public Criteria andNetEqualTo(Byte value) {
            addCriterion("`net` =", value, "net");
            return (Criteria) this;
        }

        public Criteria andNetNotEqualTo(Byte value) {
            addCriterion("`net` <>", value, "net");
            return (Criteria) this;
        }

        public Criteria andNetGreaterThan(Byte value) {
            addCriterion("`net` >", value, "net");
            return (Criteria) this;
        }

        public Criteria andNetGreaterThanOrEqualTo(Byte value) {
            addCriterion("`net` >=", value, "net");
            return (Criteria) this;
        }

        public Criteria andNetLessThan(Byte value) {
            addCriterion("`net` <", value, "net");
            return (Criteria) this;
        }

        public Criteria andNetLessThanOrEqualTo(Byte value) {
            addCriterion("`net` <=", value, "net");
            return (Criteria) this;
        }

        public Criteria andNetIn(List<Byte> values) {
            addCriterion("`net` in", values, "net");
            return (Criteria) this;
        }

        public Criteria andNetNotIn(List<Byte> values) {
            addCriterion("`net` not in", values, "net");
            return (Criteria) this;
        }

        public Criteria andNetBetween(Byte value1, Byte value2) {
            addCriterion("`net` between", value1, value2, "net");
            return (Criteria) this;
        }

        public Criteria andNetNotBetween(Byte value1, Byte value2) {
            addCriterion("`net` not between", value1, value2, "net");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("`channel` is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("`channel` is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(Byte value) {
            addCriterion("`channel` =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(Byte value) {
            addCriterion("`channel` <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(Byte value) {
            addCriterion("`channel` >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(Byte value) {
            addCriterion("`channel` >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(Byte value) {
            addCriterion("`channel` <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(Byte value) {
            addCriterion("`channel` <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<Byte> values) {
            addCriterion("`channel` in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<Byte> values) {
            addCriterion("`channel` not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(Byte value1, Byte value2) {
            addCriterion("`channel` between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(Byte value1, Byte value2) {
            addCriterion("`channel` not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("`version` is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("`version` is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Byte value) {
            addCriterion("`version` =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Byte value) {
            addCriterion("`version` <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Byte value) {
            addCriterion("`version` >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Byte value) {
            addCriterion("`version` >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Byte value) {
            addCriterion("`version` <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Byte value) {
            addCriterion("`version` <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Byte> values) {
            addCriterion("`version` in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Byte> values) {
            addCriterion("`version` not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Byte value1, Byte value2) {
            addCriterion("`version` between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Byte value1, Byte value2) {
            addCriterion("`version` not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andFinenessIsNull() {
            addCriterion("`fineness` is null");
            return (Criteria) this;
        }

        public Criteria andFinenessIsNotNull() {
            addCriterion("`fineness` is not null");
            return (Criteria) this;
        }

        public Criteria andFinenessEqualTo(Byte value) {
            addCriterion("`fineness` =", value, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessNotEqualTo(Byte value) {
            addCriterion("`fineness` <>", value, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessGreaterThan(Byte value) {
            addCriterion("`fineness` >", value, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessGreaterThanOrEqualTo(Byte value) {
            addCriterion("`fineness` >=", value, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessLessThan(Byte value) {
            addCriterion("`fineness` <", value, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessLessThanOrEqualTo(Byte value) {
            addCriterion("`fineness` <=", value, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessIn(List<Byte> values) {
            addCriterion("`fineness` in", values, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessNotIn(List<Byte> values) {
            addCriterion("`fineness` not in", values, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessBetween(Byte value1, Byte value2) {
            addCriterion("`fineness` between", value1, value2, "fineness");
            return (Criteria) this;
        }

        public Criteria andFinenessNotBetween(Byte value1, Byte value2) {
            addCriterion("`fineness` not between", value1, value2, "fineness");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("`color` is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("`color` is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(Byte value) {
            addCriterion("`color` =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(Byte value) {
            addCriterion("`color` <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(Byte value) {
            addCriterion("`color` >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(Byte value) {
            addCriterion("`color` >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(Byte value) {
            addCriterion("`color` <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(Byte value) {
            addCriterion("`color` <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<Byte> values) {
            addCriterion("`color` in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<Byte> values) {
            addCriterion("`color` not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(Byte value1, Byte value2) {
            addCriterion("`color` between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(Byte value1, Byte value2) {
            addCriterion("`color` not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andMonthsIsNull() {
            addCriterion("`months` is null");
            return (Criteria) this;
        }

        public Criteria andMonthsIsNotNull() {
            addCriterion("`months` is not null");
            return (Criteria) this;
        }

        public Criteria andMonthsEqualTo(Byte value) {
            addCriterion("`months` =", value, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsNotEqualTo(Byte value) {
            addCriterion("`months` <>", value, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsGreaterThan(Byte value) {
            addCriterion("`months` >", value, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsGreaterThanOrEqualTo(Byte value) {
            addCriterion("`months` >=", value, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsLessThan(Byte value) {
            addCriterion("`months` <", value, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsLessThanOrEqualTo(Byte value) {
            addCriterion("`months` <=", value, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsIn(List<Byte> values) {
            addCriterion("`months` in", values, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsNotIn(List<Byte> values) {
            addCriterion("`months` not in", values, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsBetween(Byte value1, Byte value2) {
            addCriterion("`months` between", value1, value2, "months");
            return (Criteria) this;
        }

        public Criteria andMonthsNotBetween(Byte value1, Byte value2) {
            addCriterion("`months` not between", value1, value2, "months");
            return (Criteria) this;
        }

        public Criteria andMonth_costIsNull() {
            addCriterion("`month_cost` is null");
            return (Criteria) this;
        }

        public Criteria andMonth_costIsNotNull() {
            addCriterion("`month_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andMonth_costEqualTo(Integer value) {
            addCriterion("`month_cost` =", value, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costNotEqualTo(Integer value) {
            addCriterion("`month_cost` <>", value, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costGreaterThan(Integer value) {
            addCriterion("`month_cost` >", value, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`month_cost` >=", value, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costLessThan(Integer value) {
            addCriterion("`month_cost` <", value, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costLessThanOrEqualTo(Integer value) {
            addCriterion("`month_cost` <=", value, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costIn(List<Integer> values) {
            addCriterion("`month_cost` in", values, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costNotIn(List<Integer> values) {
            addCriterion("`month_cost` not in", values, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costBetween(Integer value1, Integer value2) {
            addCriterion("`month_cost` between", value1, value2, "month_cost");
            return (Criteria) this;
        }

        public Criteria andMonth_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`month_cost` not between", value1, value2, "month_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costIsNull() {
            addCriterion("`total_cost` is null");
            return (Criteria) this;
        }

        public Criteria andTotal_costIsNotNull() {
            addCriterion("`total_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_costEqualTo(Integer value) {
            addCriterion("`total_cost` =", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costNotEqualTo(Integer value) {
            addCriterion("`total_cost` <>", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costGreaterThan(Integer value) {
            addCriterion("`total_cost` >", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`total_cost` >=", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costLessThan(Integer value) {
            addCriterion("`total_cost` <", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costLessThanOrEqualTo(Integer value) {
            addCriterion("`total_cost` <=", value, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costIn(List<Integer> values) {
            addCriterion("`total_cost` in", values, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costNotIn(List<Integer> values) {
            addCriterion("`total_cost` not in", values, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costBetween(Integer value1, Integer value2) {
            addCriterion("`total_cost` between", value1, value2, "total_cost");
            return (Criteria) this;
        }

        public Criteria andTotal_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`total_cost` not between", value1, value2, "total_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costIsNull() {
            addCriterion("`buyout_cost` is null");
            return (Criteria) this;
        }

        public Criteria andBuyout_costIsNotNull() {
            addCriterion("`buyout_cost` is not null");
            return (Criteria) this;
        }

        public Criteria andBuyout_costEqualTo(Integer value) {
            addCriterion("`buyout_cost` =", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costNotEqualTo(Integer value) {
            addCriterion("`buyout_cost` <>", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costGreaterThan(Integer value) {
            addCriterion("`buyout_cost` >", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costGreaterThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost` >=", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costLessThan(Integer value) {
            addCriterion("`buyout_cost` <", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costLessThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost` <=", value, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costIn(List<Integer> values) {
            addCriterion("`buyout_cost` in", values, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costNotIn(List<Integer> values) {
            addCriterion("`buyout_cost` not in", values, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costBetween(Integer value1, Integer value2) {
            addCriterion("`buyout_cost` between", value1, value2, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andBuyout_costNotBetween(Integer value1, Integer value2) {
            addCriterion("`buyout_cost` not between", value1, value2, "buyout_cost");
            return (Criteria) this;
        }

        public Criteria andMonths2IsNull() {
            addCriterion("`months2` is null");
            return (Criteria) this;
        }

        public Criteria andMonths2IsNotNull() {
            addCriterion("`months2` is not null");
            return (Criteria) this;
        }

        public Criteria andMonths2EqualTo(Byte value) {
            addCriterion("`months2` =", value, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2NotEqualTo(Byte value) {
            addCriterion("`months2` <>", value, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2GreaterThan(Byte value) {
            addCriterion("`months2` >", value, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2GreaterThanOrEqualTo(Byte value) {
            addCriterion("`months2` >=", value, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2LessThan(Byte value) {
            addCriterion("`months2` <", value, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2LessThanOrEqualTo(Byte value) {
            addCriterion("`months2` <=", value, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2In(List<Byte> values) {
            addCriterion("`months2` in", values, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2NotIn(List<Byte> values) {
            addCriterion("`months2` not in", values, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2Between(Byte value1, Byte value2) {
            addCriterion("`months2` between", value1, value2, "months2");
            return (Criteria) this;
        }

        public Criteria andMonths2NotBetween(Byte value1, Byte value2) {
            addCriterion("`months2` not between", value1, value2, "months2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2IsNull() {
            addCriterion("`month_cost2` is null");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2IsNotNull() {
            addCriterion("`month_cost2` is not null");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2EqualTo(Integer value) {
            addCriterion("`month_cost2` =", value, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2NotEqualTo(Integer value) {
            addCriterion("`month_cost2` <>", value, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2GreaterThan(Integer value) {
            addCriterion("`month_cost2` >", value, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`month_cost2` >=", value, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2LessThan(Integer value) {
            addCriterion("`month_cost2` <", value, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2LessThanOrEqualTo(Integer value) {
            addCriterion("`month_cost2` <=", value, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2In(List<Integer> values) {
            addCriterion("`month_cost2` in", values, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2NotIn(List<Integer> values) {
            addCriterion("`month_cost2` not in", values, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2Between(Integer value1, Integer value2) {
            addCriterion("`month_cost2` between", value1, value2, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andMonth_cost2NotBetween(Integer value1, Integer value2) {
            addCriterion("`month_cost2` not between", value1, value2, "month_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2IsNull() {
            addCriterion("`total_cost2` is null");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2IsNotNull() {
            addCriterion("`total_cost2` is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2EqualTo(Integer value) {
            addCriterion("`total_cost2` =", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2NotEqualTo(Integer value) {
            addCriterion("`total_cost2` <>", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2GreaterThan(Integer value) {
            addCriterion("`total_cost2` >", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`total_cost2` >=", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2LessThan(Integer value) {
            addCriterion("`total_cost2` <", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2LessThanOrEqualTo(Integer value) {
            addCriterion("`total_cost2` <=", value, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2In(List<Integer> values) {
            addCriterion("`total_cost2` in", values, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2NotIn(List<Integer> values) {
            addCriterion("`total_cost2` not in", values, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2Between(Integer value1, Integer value2) {
            addCriterion("`total_cost2` between", value1, value2, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andTotal_cost2NotBetween(Integer value1, Integer value2) {
            addCriterion("`total_cost2` not between", value1, value2, "total_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2IsNull() {
            addCriterion("`buyout_cost2` is null");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2IsNotNull() {
            addCriterion("`buyout_cost2` is not null");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2EqualTo(Integer value) {
            addCriterion("`buyout_cost2` =", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2NotEqualTo(Integer value) {
            addCriterion("`buyout_cost2` <>", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2GreaterThan(Integer value) {
            addCriterion("`buyout_cost2` >", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost2` >=", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2LessThan(Integer value) {
            addCriterion("`buyout_cost2` <", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2LessThanOrEqualTo(Integer value) {
            addCriterion("`buyout_cost2` <=", value, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2In(List<Integer> values) {
            addCriterion("`buyout_cost2` in", values, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2NotIn(List<Integer> values) {
            addCriterion("`buyout_cost2` not in", values, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2Between(Integer value1, Integer value2) {
            addCriterion("`buyout_cost2` between", value1, value2, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andBuyout_cost2NotBetween(Integer value1, Integer value2) {
            addCriterion("`buyout_cost2` not between", value1, value2, "buyout_cost2");
            return (Criteria) this;
        }

        public Criteria andFree_ratioIsNull() {
            addCriterion("`free_ratio` is null");
            return (Criteria) this;
        }

        public Criteria andFree_ratioIsNotNull() {
            addCriterion("`free_ratio` is not null");
            return (Criteria) this;
        }

        public Criteria andFree_ratioEqualTo(Byte value) {
            addCriterion("`free_ratio` =", value, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioNotEqualTo(Byte value) {
            addCriterion("`free_ratio` <>", value, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioGreaterThan(Byte value) {
            addCriterion("`free_ratio` >", value, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioGreaterThanOrEqualTo(Byte value) {
            addCriterion("`free_ratio` >=", value, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioLessThan(Byte value) {
            addCriterion("`free_ratio` <", value, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioLessThanOrEqualTo(Byte value) {
            addCriterion("`free_ratio` <=", value, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioIn(List<Byte> values) {
            addCriterion("`free_ratio` in", values, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioNotIn(List<Byte> values) {
            addCriterion("`free_ratio` not in", values, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioBetween(Byte value1, Byte value2) {
            addCriterion("`free_ratio` between", value1, value2, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andFree_ratioNotBetween(Byte value1, Byte value2) {
            addCriterion("`free_ratio` not between", value1, value2, "free_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioIsNull() {
            addCriterion("`surplus_ratio` is null");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioIsNotNull() {
            addCriterion("`surplus_ratio` is not null");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioEqualTo(Byte value) {
            addCriterion("`surplus_ratio` =", value, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioNotEqualTo(Byte value) {
            addCriterion("`surplus_ratio` <>", value, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioGreaterThan(Byte value) {
            addCriterion("`surplus_ratio` >", value, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioGreaterThanOrEqualTo(Byte value) {
            addCriterion("`surplus_ratio` >=", value, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioLessThan(Byte value) {
            addCriterion("`surplus_ratio` <", value, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioLessThanOrEqualTo(Byte value) {
            addCriterion("`surplus_ratio` <=", value, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioIn(List<Byte> values) {
            addCriterion("`surplus_ratio` in", values, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioNotIn(List<Byte> values) {
            addCriterion("`surplus_ratio` not in", values, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioBetween(Byte value1, Byte value2) {
            addCriterion("`surplus_ratio` between", value1, value2, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andSurplus_ratioNotBetween(Byte value1, Byte value2) {
            addCriterion("`surplus_ratio` not between", value1, value2, "surplus_ratio");
            return (Criteria) this;
        }

        public Criteria andMarketIsNull() {
            addCriterion("`market` is null");
            return (Criteria) this;
        }

        public Criteria andMarketIsNotNull() {
            addCriterion("`market` is not null");
            return (Criteria) this;
        }

        public Criteria andMarketEqualTo(Integer value) {
            addCriterion("`market` =", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotEqualTo(Integer value) {
            addCriterion("`market` <>", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThan(Integer value) {
            addCriterion("`market` >", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThanOrEqualTo(Integer value) {
            addCriterion("`market` >=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThan(Integer value) {
            addCriterion("`market` <", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThanOrEqualTo(Integer value) {
            addCriterion("`market` <=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketIn(List<Integer> values) {
            addCriterion("`market` in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotIn(List<Integer> values) {
            addCriterion("`market` not in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketBetween(Integer value1, Integer value2) {
            addCriterion("`market` between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotBetween(Integer value1, Integer value2) {
            addCriterion("`market` not between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioIsNull() {
            addCriterion("`deposit_ratio` is null");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioIsNotNull() {
            addCriterion("`deposit_ratio` is not null");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioEqualTo(Integer value) {
            addCriterion("`deposit_ratio` =", value, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioNotEqualTo(Integer value) {
            addCriterion("`deposit_ratio` <>", value, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioGreaterThan(Integer value) {
            addCriterion("`deposit_ratio` >", value, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioGreaterThanOrEqualTo(Integer value) {
            addCriterion("`deposit_ratio` >=", value, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioLessThan(Integer value) {
            addCriterion("`deposit_ratio` <", value, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioLessThanOrEqualTo(Integer value) {
            addCriterion("`deposit_ratio` <=", value, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioIn(List<Integer> values) {
            addCriterion("`deposit_ratio` in", values, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioNotIn(List<Integer> values) {
            addCriterion("`deposit_ratio` not in", values, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioBetween(Integer value1, Integer value2) {
            addCriterion("`deposit_ratio` between", value1, value2, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratioNotBetween(Integer value1, Integer value2) {
            addCriterion("`deposit_ratio` not between", value1, value2, "deposit_ratio");
            return (Criteria) this;
        }

        public Criteria andDepositIsNull() {
            addCriterion("`deposit` is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsNotNull() {
            addCriterion("`deposit` is not null");
            return (Criteria) this;
        }

        public Criteria andDepositEqualTo(Integer value) {
            addCriterion("`deposit` =", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotEqualTo(Integer value) {
            addCriterion("`deposit` <>", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThan(Integer value) {
            addCriterion("`deposit` >", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThanOrEqualTo(Integer value) {
            addCriterion("`deposit` >=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThan(Integer value) {
            addCriterion("`deposit` <", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThanOrEqualTo(Integer value) {
            addCriterion("`deposit` <=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositIn(List<Integer> values) {
            addCriterion("`deposit` in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotIn(List<Integer> values) {
            addCriterion("`deposit` not in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositBetween(Integer value1, Integer value2) {
            addCriterion("`deposit` between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotBetween(Integer value1, Integer value2) {
            addCriterion("`deposit` not between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2IsNull() {
            addCriterion("`deposit_ratio2` is null");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2IsNotNull() {
            addCriterion("`deposit_ratio2` is not null");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2EqualTo(Integer value) {
            addCriterion("`deposit_ratio2` =", value, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2NotEqualTo(Integer value) {
            addCriterion("`deposit_ratio2` <>", value, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2GreaterThan(Integer value) {
            addCriterion("`deposit_ratio2` >", value, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`deposit_ratio2` >=", value, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2LessThan(Integer value) {
            addCriterion("`deposit_ratio2` <", value, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2LessThanOrEqualTo(Integer value) {
            addCriterion("`deposit_ratio2` <=", value, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2In(List<Integer> values) {
            addCriterion("`deposit_ratio2` in", values, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2NotIn(List<Integer> values) {
            addCriterion("`deposit_ratio2` not in", values, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2Between(Integer value1, Integer value2) {
            addCriterion("`deposit_ratio2` between", value1, value2, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit_ratio2NotBetween(Integer value1, Integer value2) {
            addCriterion("`deposit_ratio2` not between", value1, value2, "deposit_ratio2");
            return (Criteria) this;
        }

        public Criteria andDeposit2IsNull() {
            addCriterion("`deposit2` is null");
            return (Criteria) this;
        }

        public Criteria andDeposit2IsNotNull() {
            addCriterion("`deposit2` is not null");
            return (Criteria) this;
        }

        public Criteria andDeposit2EqualTo(Integer value) {
            addCriterion("`deposit2` =", value, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2NotEqualTo(Integer value) {
            addCriterion("`deposit2` <>", value, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2GreaterThan(Integer value) {
            addCriterion("`deposit2` >", value, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2GreaterThanOrEqualTo(Integer value) {
            addCriterion("`deposit2` >=", value, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2LessThan(Integer value) {
            addCriterion("`deposit2` <", value, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2LessThanOrEqualTo(Integer value) {
            addCriterion("`deposit2` <=", value, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2In(List<Integer> values) {
            addCriterion("`deposit2` in", values, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2NotIn(List<Integer> values) {
            addCriterion("`deposit2` not in", values, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2Between(Integer value1, Integer value2) {
            addCriterion("`deposit2` between", value1, value2, "deposit2");
            return (Criteria) this;
        }

        public Criteria andDeposit2NotBetween(Integer value1, Integer value2) {
            addCriterion("`deposit2` not between", value1, value2, "deposit2");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNull() {
            addCriterion("`premium` is null");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNotNull() {
            addCriterion("`premium` is not null");
            return (Criteria) this;
        }

        public Criteria andPremiumEqualTo(Integer value) {
            addCriterion("`premium` =", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotEqualTo(Integer value) {
            addCriterion("`premium` <>", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThan(Integer value) {
            addCriterion("`premium` >", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`premium` >=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThan(Integer value) {
            addCriterion("`premium` <", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThanOrEqualTo(Integer value) {
            addCriterion("`premium` <=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumIn(List<Integer> values) {
            addCriterion("`premium` in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotIn(List<Integer> values) {
            addCriterion("`premium` not in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumBetween(Integer value1, Integer value2) {
            addCriterion("`premium` between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotBetween(Integer value1, Integer value2) {
            addCriterion("`premium` not between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andSales_limitIsNull() {
            addCriterion("`sales_limit` is null");
            return (Criteria) this;
        }

        public Criteria andSales_limitIsNotNull() {
            addCriterion("`sales_limit` is not null");
            return (Criteria) this;
        }

        public Criteria andSales_limitEqualTo(Integer value) {
            addCriterion("`sales_limit` =", value, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitNotEqualTo(Integer value) {
            addCriterion("`sales_limit` <>", value, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitGreaterThan(Integer value) {
            addCriterion("`sales_limit` >", value, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitGreaterThanOrEqualTo(Integer value) {
            addCriterion("`sales_limit` >=", value, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitLessThan(Integer value) {
            addCriterion("`sales_limit` <", value, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitLessThanOrEqualTo(Integer value) {
            addCriterion("`sales_limit` <=", value, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitIn(List<Integer> values) {
            addCriterion("`sales_limit` in", values, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitNotIn(List<Integer> values) {
            addCriterion("`sales_limit` not in", values, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitBetween(Integer value1, Integer value2) {
            addCriterion("`sales_limit` between", value1, value2, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_limitNotBetween(Integer value1, Integer value2) {
            addCriterion("`sales_limit` not between", value1, value2, "sales_limit");
            return (Criteria) this;
        }

        public Criteria andSales_totalIsNull() {
            addCriterion("`sales_total` is null");
            return (Criteria) this;
        }

        public Criteria andSales_totalIsNotNull() {
            addCriterion("`sales_total` is not null");
            return (Criteria) this;
        }

        public Criteria andSales_totalEqualTo(Integer value) {
            addCriterion("`sales_total` =", value, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalNotEqualTo(Integer value) {
            addCriterion("`sales_total` <>", value, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalGreaterThan(Integer value) {
            addCriterion("`sales_total` >", value, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`sales_total` >=", value, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalLessThan(Integer value) {
            addCriterion("`sales_total` <", value, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalLessThanOrEqualTo(Integer value) {
            addCriterion("`sales_total` <=", value, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalIn(List<Integer> values) {
            addCriterion("`sales_total` in", values, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalNotIn(List<Integer> values) {
            addCriterion("`sales_total` not in", values, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalBetween(Integer value1, Integer value2) {
            addCriterion("`sales_total` between", value1, value2, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_totalNotBetween(Integer value1, Integer value2) {
            addCriterion("`sales_total` not between", value1, value2, "sales_total");
            return (Criteria) this;
        }

        public Criteria andSales_tempIsNull() {
            addCriterion("`sales_temp` is null");
            return (Criteria) this;
        }

        public Criteria andSales_tempIsNotNull() {
            addCriterion("`sales_temp` is not null");
            return (Criteria) this;
        }

        public Criteria andSales_tempEqualTo(Integer value) {
            addCriterion("`sales_temp` =", value, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempNotEqualTo(Integer value) {
            addCriterion("`sales_temp` <>", value, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempGreaterThan(Integer value) {
            addCriterion("`sales_temp` >", value, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempGreaterThanOrEqualTo(Integer value) {
            addCriterion("`sales_temp` >=", value, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempLessThan(Integer value) {
            addCriterion("`sales_temp` <", value, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempLessThanOrEqualTo(Integer value) {
            addCriterion("`sales_temp` <=", value, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempIn(List<Integer> values) {
            addCriterion("`sales_temp` in", values, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempNotIn(List<Integer> values) {
            addCriterion("`sales_temp` not in", values, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempBetween(Integer value1, Integer value2) {
            addCriterion("`sales_temp` between", value1, value2, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andSales_tempNotBetween(Integer value1, Integer value2) {
            addCriterion("`sales_temp` not between", value1, value2, "sales_temp");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("`orderno` is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("`orderno` is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(Long value) {
            addCriterion("`orderno` =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(Long value) {
            addCriterion("`orderno` <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(Long value) {
            addCriterion("`orderno` >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(Long value) {
            addCriterion("`orderno` >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(Long value) {
            addCriterion("`orderno` <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(Long value) {
            addCriterion("`orderno` <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<Long> values) {
            addCriterion("`orderno` in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<Long> values) {
            addCriterion("`orderno` not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(Long value1, Long value2) {
            addCriterion("`orderno` between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(Long value1, Long value2) {
            addCriterion("`orderno` not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andYmdhmsIsNull() {
            addCriterion("`ymdhms` is null");
            return (Criteria) this;
        }

        public Criteria andYmdhmsIsNotNull() {
            addCriterion("`ymdhms` is not null");
            return (Criteria) this;
        }

        public Criteria andYmdhmsEqualTo(String value) {
            addCriterion("`ymdhms` =", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsNotEqualTo(String value) {
            addCriterion("`ymdhms` <>", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsGreaterThan(String value) {
            addCriterion("`ymdhms` >", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsGreaterThanOrEqualTo(String value) {
            addCriterion("`ymdhms` >=", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsLessThan(String value) {
            addCriterion("`ymdhms` <", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsLessThanOrEqualTo(String value) {
            addCriterion("`ymdhms` <=", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsLike(String value) {
            addCriterion("`ymdhms` like", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsNotLike(String value) {
            addCriterion("`ymdhms` not like", value, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsIn(List<String> values) {
            addCriterion("`ymdhms` in", values, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsNotIn(List<String> values) {
            addCriterion("`ymdhms` not in", values, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsBetween(String value1, String value2) {
            addCriterion("`ymdhms` between", value1, value2, "ymdhms");
            return (Criteria) this;
        }

        public Criteria andYmdhmsNotBetween(String value1, String value2) {
            addCriterion("`ymdhms` not between", value1, value2, "ymdhms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_price_1
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 23 15:33:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}