package com.zdd.risk.dao;

import com.zdd.risk.bean.OrderCost;
import com.zdd.risk.bean.OrderCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IOrderCostDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    long countByExample(OrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int deleteByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int insert(OrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int insertSelective(OrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    List<OrderCost> selectByExampleWithBLOBs(OrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    List<OrderCost> selectByExample(OrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    OrderCost selectByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderCost record, @Param("example") OrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") OrderCost record, @Param("example") OrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int updateByExample(@Param("record") OrderCost record, @Param("example") OrderCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int updateByPrimaryKeySelective(OrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(OrderCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cost_1
     *
     * @mbg.generated Fri Nov 23 15:34:39 CST 2018
     */
    int updateByPrimaryKey(OrderCost record);

    OrderCost selectByOrderid(String orderid);
}