package com.zdd.risk.dao;

import com.zdd.risk.bean.ProductPrice;
import com.zdd.risk.bean.ProductPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface IProductPriceDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    long countByExample(ProductPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int deleteByPrimaryKey(Integer priceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int insert(ProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int insertSelective(ProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    List<ProductPrice> selectByExampleWithBLOBs(ProductPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    List<ProductPrice> selectByExample(ProductPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    ProductPrice selectByPrimaryKey(Integer priceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductPrice record, @Param("example") ProductPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProductPrice record, @Param("example") ProductPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int updateByExample(@Param("record") ProductPrice record, @Param("example") ProductPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int updateByPrimaryKeySelective(ProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_1
     *
     * @mbg.generated Fri Nov 23 15:33:39 CST 2018
     */
    int updateByPrimaryKey(ProductPrice record);

    @Select(value = "select * from product_price_1 where priceid=#{priceid} and productid=#{productid}")
    ProductPrice selectByProductIdAndPriceid1(@Param(value = "productid") Integer productid,@Param(value = "priceid") Integer priceid);

    @Select(value = "select * from product_price_2 where priceid=#{priceid} and productid=#{productid}")
    ProductPrice selectByProductIdAndPriceid2(@Param(value = "productid") Integer productid,@Param(value = "priceid") Integer priceid);

    @Select(value = "select * from product_price_3 where priceid=#{priceid} and productid=#{productid}")
    ProductPrice selectByProductIdAndPriceid3(@Param(value = "productid") Integer productid,@Param(value = "priceid") Integer priceid);

    @Select(value = "select * from product_price_4 where priceid=#{priceid} and productid=#{productid}")
    ProductPrice selectByProductIdAndPriceid4(@Param(value = "productid") Integer productid,@Param(value = "priceid") Integer priceid);


}